---
image: node:latest
services:
- mysql:latest
- redis:latest
cache:
  paths:
  - node_modules/

stages:
  - testing
  - testing_db
  - deploy

test_async:
  stage: testing
  script:
  - npm install
  - node ./specs/start.js ./specs/async.spec.js
test_db:
  stage: testing_db
  script:
  - npm install
  - node ./specs/start.js ./specs/db-postgres.spec.js
deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production
  only:
    - master
